const collectionsTypes = [
  {
    "id": 0,
    "name": "Bio 2wö",
    "iconNr": 24,
    "farbeRgb": "228B22",
    "material": [],
  },
  {
    "id": 1,
    "name": "Gelber Sack",
    "iconNr": 12,
    "farbeRgb": "FFD700",
    "material": [],
  },
  {
    "id": 2,
    "name": "Altpapier 2500",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 3,
    "name": "Altpapier 5000",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 4,
    "name": "Altpapier 4wö",
    "iconNr": 11,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 5,
    "name": "Altpapier 4wö 1100",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 6,
    "name": "Altpapier 4wö 770",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 7,
    "name": "Restabfall",
    "iconNr": 28,
    "farbeRgb": "C0C0C0C0",
    "material": [],
  },
  {
    "id": 8,
    "name": "Restabfall 1100",
    "iconNr": 34,
    "farbeRgb": "C0C0C0C0",
    "material": [],
  },
  {
    "id": 9,
    "name": "Restabfall 2500",
    "iconNr": 34,
    "farbeRgb": "C0C0C0C0",
    "material": [],
  },
  {
    "id": 10,
    "name": "Restabfall 770",
    "iconNr": 34,
    "farbeRgb": "C0C0C0C0",
    "material": [],
  },
  {
    "id": 11,
    "name": "Restabfall 2wö",
    "iconNr": 73,
    "farbeRgb": "d20e0e",
    "material": [],
  },
  {
    "id": 12,
    "name": "Restabfall 2wö 1100",
    "iconNr": 70,
    "farbeRgb": "d20e0e",
    "material": [],
  },
  {
    "id": 13,
    "name": "Restabfall 2wö 770",
    "iconNr": 70,
    "farbeRgb": "d20e0e",
    "material": [],
  },
  {
    "id": 14,
    "name": "Restabfall 4wö",
    "iconNr": 53,
    "farbeRgb": "f9f4ea",
    "material": [],
  },
  {
    "id": 15,
    "name": "Restabfall 4wö 770",
    "iconNr": 70,
    "farbeRgb": "f9f4ea",
    "material": [],
  },
  {
    "id": 16,
    "name": "Restabfall wö 5000",
    "iconNr": 70,
    "farbeRgb": "f9f4ea",
    "material": [],
  },
  {
    "id": 17,
    "name": "Altpapier 1100",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 18,
    "name": "Restabfall 4wö 1100",
    "iconNr": 34,
    "farbeRgb": "C0C0C0C0",
    "material": [],
  },
  {
    "id": 19,
    "name": "Altpapier wö",
    "iconNr": 11,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 20,
    "name": "Altpapier wö 770",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 21,
    "name": "Altpapier 2wö",
    "iconNr": 11,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 22,
    "name": "Altpapier 2wö 1100",
    "iconNr": 68,
    "farbeRgb": "0074ff",
    "material": [],
  },
  {
    "id": 23,
    "name": "Weihnachtsbaum",
    "iconNr": 14,
    "farbeRgb": "7CFC00",
    "material": [],
  },
];
